{% set name = "splitvar" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/coecms/splitvar/archive/master.zip

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - splitvar

about:
  home: http://github.com/coecms/splitvar
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: Aggregate and split netCDF data to be suitable for distribution via THREDDs
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - aidanheerdegen
