{% set name = "dreqPy" %}
{% set version = "1.0.30" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2bdc8e3a7168392858e22b36d5b1e7f52d18bc70cbb38a1eef8e8c67096fd4a8

build:
  noarch: python
  number: 0
  entry_points:
    - drq = dreqPy.dreqCmdl:main_entry
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - xlsxwriter
  imports:
    - dreqPy
    - dreqPy.examples
    - dreqPy.extensions
  commands:
    - drq -h

about:
  home: http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/01.00.28
  license: MIT
  license_family: MIT
  summary: CMIP6 Data Request Python API
