{% set version='1.1.2' %}

package:
  name: dataset
  version: {{version}}

source:
  url: https://pypi.python.org/packages/source/d/dataset/dataset-{{version}}.tar.gz
  sha256: 06e6e8166a2ce12524ffbed97b82866caeaa2dd8e85ee65baccf3b815528e22e

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - sqlalchemy >=1.1.2
    - alembic >=0.6.2
    - six >=1.11.0

test:
  # Python imports
  imports:
    - dataset

about:
  home: http://github.com/pudo/dataset
  license: MIT License
  summary: 'Toolkit for Python-based data processing.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
