package:
    name: mule
    version: '2020.01.1'

source:
    svn_url: https://code.metoffice.gov.uk/svn/um/mule/trunk
    svn_rev: 79553

build:
    noarch: python
    number: 0
    script: |
        pushd mule; python -m pip install --no-deps --ignore-installed .; popd
        pushd um_utils; python -m pip install --no-deps --ignore-installed .; popd

requirements:
    host:
        - python
        - pip
    run:
        - python
        - numpy
        - six

test:
    imports:
        - mule
    commands:
        - mule-pumf --help
        - mule-version

about:
    home: https://code.metoffice.gov.uk/trac/um
    license: BSD
    license_file: mule/LICENCE.txt
    summary: Unified Model Fields File interface
