package:
    name: improver
    version: '0.4.0'

source:
    git_url: https://github.com/metoppv/improver
    git_rev: '0.4.0'

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - six

test:
    imports:
        - improver

about:
    home: https://github.com/metoppv/improver
    license: BSD
    license_file: LICENCE
    summary: IMPROVER is a library of algorithms for meteorological post-processing and verification.
