travis:
  secure:
    BINSTAR_TOKEN: nuk+NMJiEBXn+h5/3+PpO0gefM2QZxPUTejjc7LC4iCW2AkdZ4dVlCeI1jynZbMQC4b8sk6KkJBVF//grHSoPb3Due+jKaelBbcv48tJg5vXH14w9AM7V9x/6KMQtKK2xAtulw7Th+/Zs6TfJ7wRiKt1zmCtUki3Ftytr6LQMC98BKccd1l9XIEYZPOfGDX06v9S86AD25TZW6DgFSafXGRTjpCYlmkOwa+BlRvX8Fdc/1kf80DbS78FU5M6lt41NPCUprPD5KVl6BtSf9U8BoDiAJ+lf5FzBEFBmg0EVyxYXZEP2R8BI8XqG82cNlB0btl1cczGcoNejbH+aMJBdHw1G+W9egGR/LQTbZasWLas6HeWhBtEhyFPgdHu+2Nxv3qB7kVzU7e9qCX23nNVvF71Q7Yx8orjXViG/lMj0i9M5v/Ch5Vv7HwfnWsR8ffU67LHpygZ2DbdG0Nrc2Mqs7UeJtV4t3lDEjTuXYZFwy0teHEO0aIH9Q1A2rgJ+tybPNdNut4Ztm/PQ0sWA3/sHLLvVxADU3IiDEy5f074KkYzHDp+fHVkKmOsMJ9ZBLd8HEMJkT1kT/Z2XOSEbcalQh3fNmkpRZpyGOnySLYCMdRErmjTckx1DoQsqXA8BNEPX5dFi1w/icMHDvIqVOhfzzKibrQ09OMw07hKYlBPyXs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  osx: circle
