travis:
  secure:
    BINSTAR_TOKEN: Ox/yuhx+NOWszJJ4GmXWv7u+/MpNZe4av/03vQFFGj15r9AaT9FzHAbJNoQAxFyO3y1gJ+7xIJzZokL+xWYgeJfdp5bGyJMGjIDGed4wCPfy41mSHPf/jcq++05xptYzad5EQypBZFHgQ65ODaq2p++3krxEedHUNI27Zb5HXn8qJ4AaPmTNmzIj+ZjJZoS8XordY+3f3JEL9fnTHvFylHonJGXu6uhb8Fkdh13m9dUQHQUDWnTd+04gOuy35vvH59zRyw95pC9ZvueetorzVWWJOst/SmLfV2lnX2qoeSGHjTdLyuGL8KBE0G1G34pOaAGymaLCK48bynnI7Ff5T30B0PsVUJTUnQdqCB0TDrddjYs5jwRe6X5MR8pnzdiJis0EkHY+ODuoY1xTumKmvWhoEIuSO1RvzQKcKMYG/u8aQ+nQD5TvIsPIlsPS9LaaFSA/jCypIIsHO7KweU+0fKtZMO4m0+MKJdGPHeVms2KtXT72j90l0Uq0WtGHqgm4CZwpidKevaXM76G/nmKyRs4u2IQ2i82bS15HxEb06T1EAYUKuN1syx/T76PDuG1ydgFyy+gfS5pZpDK9Kej0pYcoSaD/x1jd+MDtqx0ZyZuta0DNwX9jh38yBiw0wSshua345jYWgdAwFHsQyNmFYLbqct6ATBD0VokHiBliCQQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
