{% set version='0.1.3' %}

package:
    name: pymunge
    version: '{{version}}'

source:
    url: https://github.com/nomadictype/pymunge/archive/{{version}}.tar.gz

build:
    noarch: python
    number: 1
    script: {{PYTHON}} -m pip install --no-deps --ignore-installed .

requirements:
    host:
        - python
        - pip
    run:
        - python

test:
#    requires:
#        - pytest
    imports:
        - pymunge
#    source_files:
#        - tests
#    commands:
#        - py.test tests

about:
    home: https://github.com/nomadictype/pymunge
    license: LGPL3
    license_file: LICENSE.txt
    summary: A Python interface to MUNGE 
