package:
    name: marineheatwaves
    version: {{ GIT_DESCRIBE_TAG }}

source:
    git_url: https://github.com/ecjoliver/marineHeatWaves

build:
    script: "{{ PYTHON }} -m pip install . --no-deps"
    noarch: python
    number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
    host:
        - python
        - pip
    run:
        - python >=3.6
        - numpy
        - scipy

test:
    imports:
        - marineHeatWaves
