package:
  name: normality
  version: "0.4.4"

source:
  fn: normality-0.4.4.tar.gz
  url: https://pypi.python.org/packages/80/4e/d7886f8fc39c386ba8e19ec465daf6ad81d2b005db4d285f0fb07491c864/normality-0.4.4.tar.gz
  md5: eaff7550219a3b7e123b9c67e0952def
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - normality = normality:main
    #
    # Would create an entry point called normality that calls normality.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six
    - chardet

  run:
    - python
    - six
    - chardet

test:
  # Python imports
  imports:
    - normality

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/pudo/normality
  license: MIT License
  summary: 'Micro-library to normalize text strings'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
