package:
    name: cartopy_userconfig
    version: '1.0.gadi'

source:
    path: .

build:
    script: python -m pip install --no-deps --ignore-installed .
    noarch: python

requirements:
    host:
      - python

test:
    imports:
        - cartopy_userconfig
