{% set name = "celluloid" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 568b1512c4a97483759e9436c3f3e5dc5566da350179aa1872992ec8d82706e1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - pip
    - python
    - flit
  run:
    - matplotlib
    - python

about:
  home: "https://github.com/jwkvam/celluloid"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Easy matplotlib animation."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
