package:
    name: openmpi
    version: 4.0.2

source:
    path: .

build:
    number: 1
    string: gadi

requirements:
    run:
        - mpi 1.0 openmpi

test:
    requires:
        - mpi4py
    files:
        - test_mpi.py
    commands:
        - mpirun -n 4 python test_mpi.py
